services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  web:
    image: keygen/api:latest
    ports:
      - "3000:3000"
    command: "web"
    environment:
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      ENCRYPTION_DETERMINISTIC_KEY: "${ENCRYPTION_DETERMINISTIC_KEY}"
      ENCRYPTION_PRIMARY_KEY: "${ENCRYPTION_PRIMARY_KEY}"
      ENCRYPTION_KEY_DERIVATION_SALT: "${ENCRYPTION_KEY_DERIVATION_SALT}"
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
      REDIS_URL: "redis://redis:6379"
      KEYGEN_ACCOUNT_ID: "${KEYGEN_ACCOUNT_ID}"
      KEYGEN_EDITION: "${KEYGEN_EDITION}"
      KEYGEN_MODE: "${KEYGEN_MODE}"
      KEYGEN_HOST: "${KEYGEN_HOST}"
    volumes:
      - keygen:/etc/keygen
    links:
      - postgres
      - redis

  worker:
    image: keygen/api:latest
    command: "worker"
    environment:
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      ENCRYPTION_DETERMINISTIC_KEY: "${ENCRYPTION_DETERMINISTIC_KEY}"
      ENCRYPTION_PRIMARY_KEY: "${ENCRYPTION_PRIMARY_KEY}"
      ENCRYPTION_KEY_DERIVATION_SALT: "${ENCRYPTION_KEY_DERIVATION_SALT}"
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
      REDIS_URL: "redis://redis:6379"
      KEYGEN_ACCOUNT_ID: "${KEYGEN_ACCOUNT_ID}"
      KEYGEN_EDITION: "${KEYGEN_EDITION}"
      KEYGEN_MODE: "${KEYGEN_MODE}"
      KEYGEN_HOST: "${KEYGEN_HOST}"
    volumes:
      - keygen:/etc/keygen
    links:
      - postgres
      - redis
  
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
volumes:
  keygen:
  postgres:
  redis:
  caddy_data:
  caddy_config:
